### ISSUE TITLE
Role fails with Ansible 2.7.6 and Python3

### ISSUE THREAD

**Issue by kklimonda** [juju4/ansible-auditd#1]
ansible is throwing the following error when executed on ubuntu 18.04 targets with python3:

`failed: [omitted] (item=05-exclusions) => {"changed": false, "item": "05-exclusions", "msg": "AnsibleError: Unexpected templating type error occurred on ({{ ansible_managed | comment }}\n# Exclusions\n{% for r in auditd_exclusion_rules %}\n{{ r }}\n{% endfor %}\n{% if (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= 16) or (ansible_os_family == \"RedHat\" and ansible_distribution_major_version >= '7') %}\n{% for r in auditd_exclusion_rules2 %}\n{{ r }}\n{% endfor %}\n{% endif %}\n\n): '>=' not supported between instances of 'AnsibleUnsafeText' and 'int'"}
`

I'm assuming it's this report: https://github.com/ansible/ansible/issues/50388 where the answer is to fix the code, not compare strings with ints.

**Comment by juju4** [comment]
Interesting. I think I saw that a few times but not widely, so I started fixing it in few places but not everywhere...
Strange because python3 is by default the only python since xenial.

Ah, but the reason, I don't see it in travis is because image is 14.04 and can't use containers for auditd testing...
since xenial is available since a few months, should switch to it.

PR merged
