### ISSUE TITLE
Socket auditing rules fail to load with "Multiple rule insert/delete operations are not allowed"

### ISSUE THREAD

**Issue by smatterchew** [juju4/ansible-auditd#14]
Running auditd version **audit-2.8.5-4.el7.x86_64** on oracle uek kernel **4.14.35-1902.300.11.el7uek.x86_64**

When I set`auditd_log_all_socket: true` in defaults/main.yml, all of the rules are placed into `/etc/audit/rules.d/90-extra.rules` as expected, but they are all commented out.

If I uncomment the rules and manually attempt to load them I get an error.
`[root@localhost rules.d]# auditctl -a exit,always -F arch=b32 -a0=2 -F a1=1 -S socket -k socket_call_ipv4_tcp`
`Multiple rule insert/delete operations are not allowed`

I'm not an expert on audit rules, but I think the rule itself may be written wrong.  I know the error is with `-a0=2` because when I remove it the rule is accepted without comment.  It looks like you are attempting to select some fields to go into the log?  Sould the entry be `-F a0=2` instead?  When I change the rule this way, it is accepted by auditd.

**Comment by juju4** [comment]
This part of the code seems a bit old
https://github.com/juju4/ansible-auditd/blame/master/templates/90-extra.rules.j2#L53

I don't remember exactly but I suspect that when I tested it was too noisy, so I likely commented it and after put the if condition.
good catch on missing 'F'

added non-default options to test/default

should be fixed with https://github.com/juju4/ansible-auditd/commit/a7eb8ee46a1a0e93d33db7e3bd54c5070ae608f5
only devel currently, seems travis has an issue...

**Comment by juju4** [comment]
Closing old issue as no feedback
